version: "3.2"
services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=docker_test
      - MYSQL_USER=test_user2
      - MYSQL_PASSWORD=test_user2
      - MYSQL_ROOT_PASSWORD=2972
    ports:
      - "3302:3306"
    networks:
      - db-net

  backend:
    restart: always
    container_name: django_container
    command: bash -c "cd ./src && python check_db.py --service-name db --ip db --port 3306 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/src/settings.ini
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
